version: '3.8'

services:

  postgres:
    image: postgres:latest
    container_name: academy_db_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123!
      POSTGRES_DB: AcademyDb
    expose:
      - 5432
    ports:
      - "5432:5432"  
    networks:
      - academy-network
    volumes:
      - academy_db_volume:/var/lib/postgresql/data
    restart: always

volumes:
  academy_db_volume:

networks:
  academy-network:
    driver: bridge

